nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Session-ID']
        expose_headers: ['Content-Disposition']
        max_age: 3600
        hosts: []
        origin_regex: false
    paths:
        '^/api/':
            allow_credentials: true 
            allow_origin: ['*']
            allow_headers: ['Content-Type', 'Authorization', 'X-Session-ID']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
